### ISSUE TITLE
'Unhandled match case 'Created'' error with existing data in Spatie Activity Logs table.

### ISSUE THREAD

**Issue by koppa53** [rmsramos/activitylog#21]
### What happened?

I tried installing this new plugin with existing data in activity logs however i keep receiving this error when i load the page. 'Unhandled match case 'Created''

### How to reproduce the bug

Install the plugin with existing data/logs. The logs was previously generated with the plugin z3d0x/filament-logger.

### Package Version

1.0

### PHP Version

8.3.3

### Laravel Version

11.10.0

### Which operating systems does with happen with?

Windows

**Comment by rmsramos** [comment]
Can you give me more information about the error? If possible example of code and print of the error.

**Comment by koppa53** [comment]
![image](https://github.com/rmsramos/activitylog/assets/72752456/520445fc-308b-48a9-a175-023fe2ef5178)

**Comment by rmsramos** [comment]
Hi guys, today I'm going to check this out.

**Comment by rmsramos** [comment]
Hi guys, fixed in [v1.0.2](https://github.com/rmsramos/activitylog/releases/tag/v1.0.2)
I hadn't really left a default return value for other events. Update the package and confirm if it is working normally.
