### ISSUE TITLE
[Bug]: configuration file collision

### ISSUE THREAD

**Issue by mrvnklm** [rmsramos/activitylog#22]
### What happened?

pulishing the config file of your package collides with the publishing of the `spatie/activitylog` config file, as they both have the same name

### How to reproduce the bug

`php artisan vendor:publish --tag="activitylog-config"`

### Package Version

latest

### PHP Version

8.3

### Laravel Version

11

**Comment by rmsramos** [comment]
fixed in release  [ v1.0.2](https://github.com/rmsramos/activitylog/releases/tag/v1.0.2)

please update package, and delete old file and publish new.
