### ISSUE TITLE
[Bug]: foreach() argument must be of type array|object, null given

### ISSUE THREAD

**Issue by momostafa** [rmsramos/activitylog#24]
### What happened?

if I enable properties and 1 of the records has null properties I get this error 

foreach() argument must be of type array|object, null given

### How to reproduce the bug

go to published activity log view enable properties column if properties value is null you will get above error

### Package Version

1.0.2

### PHP Version

8.2.19

### Laravel Version

11.10.0

### Which operating systems does with happen with?

macOS

### Notes

nice interface thank you

**Comment by rmsramos** [comment]
I don't understand why you are saving some null property , Wouldn't it be better to use logOnlyDirty() , logging only what was actually updated?

**Comment by momostafa** [comment]
Hi,

only the properties column is null when there is no old log to compare to 

```php
   public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()

            ->useLogName("User Logs")
            ->logExcept(['password', 
             'remember_token',
             ]);
            ->logAll();
    }
``` 
 and I activated properties column to see what it has as this is the first time i am using  your plugin and spatie activity log in general

**Comment by momostafa** [comment]
Okay, thanks for your inputs

**Comment by rmsramos** [comment]
As soon as I have time I will check this part, to avoid errors if there are any null fields.
Thanks for testing the plugin

**Comment by momostafa** [comment]
> As soon as I have time I will check this part, to avoid errors if there are any null fields. Thanks for testing the plugin

That will be great, Thank you
for now during my testing I have added the default value to []

```php
    public static function getPropertiesColumnCompoment(): Column
    {
        return ViewColumn::make('properties')
            ->label(__('activitylog::tables.columns.properties.label'))
            ->default([])
            ->view('activitylog::filament.tables.columns.activity-logs-properties')
            ->toggleable(isToggledHiddenByDefault: true);
    }
```
