### ISSUE TITLE
[Bug]: Error in timeline view for User. 

### ISSUE THREAD

**Issue by koppa53** [rmsramos/activitylog#25]
### What happened?

Im getting this error when i try to view the timeline table action.

`Rmsramos\Activitylog\Infolists\Components\TimeLineTitleEntry::getModifiedState(): Return value must be of type ?Illuminate\Support\HtmlString, string returned`

![image](https://github.com/rmsramos/activitylog/assets/72752456/36179349-094f-4636-aefa-85fb7a716937)

### How to reproduce the bug

Has existing data generated in previous logger.

### Package Version

1.0.2

### PHP Version

8.3.3

### Laravel Version

11.10.0

**Comment by rmsramos** [comment]
You can public GitHub repository which reproduces the problem?
Note: Please do not link to your actual project
